offset_temperature:
  name: "Offset Temperature"
  description: "Offsets the temperature to the given value"
  target:
    entity:
      integration: "my_sensor"
      domain: sensor
  fields:
    by:
      name: "Offset by"
      description: "Offsets the temperature by the specified amount"
      required: false
      default: 0
      selector:
        number:
          min: -40
          max: 50
